
export const IsdCode=
[
    {
       "name":"Afghanistan",
       "flag":"🇦🇫",
       "code":"AF",
       "dial_code":"+93"
    },
    {
       "name":"Åland Islands",
       "flag":"🇦🇽",
       "code":"AX",
       "dial_code":"+358"
    },
    {
       "name":"Albania",
       "flag":"🇦🇱",
       "code":"AL",
       "dial_code":"+355"
    },
    {
       "name":"Algeria",
       "flag":"🇩🇿",
       "code":"DZ",
       "dial_code":"+213"
    },
    {
       "name":"American Samoa",
       "flag":"🇦🇸",
       "code":"AS",
       "dial_code":"+1684"
    },
    {
       "name":"Andorra",
       "flag":"🇦🇩",
       "code":"AD",
       "dial_code":"+376"
    },
    {
       "name":"Angola",
       "flag":"🇦🇴",
       "code":"AO",
       "dial_code":"+244"
    },
    {
       "name":"Anguilla",
       "flag":"🇦🇮",
       "code":"AI",
       "dial_code":"+1264"
    },
    {
       "name":"Antarctica",
       "flag":"🇦🇶",
       "code":"AQ",
       "dial_code":"+672"
    },
    {
       "name":"Antigua and Barbuda",
       "flag":"🇦🇬",
       "code":"AG",
       "dial_code":"+1268"
    },
    {
       "name":"Argentina",
       "flag":"🇦🇷",
       "code":"AR",
       "dial_code":"+54"
    },
    {
       "name":"Armenia",
       "flag":"🇦🇲",
       "code":"AM",
       "dial_code":"+374"
    },
    {
       "name":"Aruba",
       "flag":"🇦🇼",
       "code":"AW",
       "dial_code":"+297"
    },
    {
       "name":"Australia",
       "flag":"🇦🇺",
       "code":"AU",
       "dial_code":"+61"
    },
    {
       "name":"Austria",
       "flag":"🇦🇹",
       "code":"AT",
       "dial_code":"+43"
    },
    {
       "name":"Azerbaijan",
       "flag":"🇦🇿",
       "code":"AZ",
       "dial_code":"+994"
    },
    {
       "name":"Bahamas",
       "flag":"🇧🇸",
       "code":"BS",
       "dial_code":"+1242"
    },
    {
       "name":"Bahrain",
       "flag":"🇧🇭",
       "code":"BH",
       "dial_code":"+973"
    },
    {
       "name":"Bangladesh",
       "flag":"🇧🇩",
       "code":"BD",
       "dial_code":"+880"
    },
    {
       "name":"Barbados",
       "flag":"🇧🇧",
       "code":"BB",
       "dial_code":"+1246"
    },
    {
       "name":"Belarus",
       "flag":"🇧🇾",
       "code":"BY",
       "dial_code":"+375"
    },
    {
       "name":"Belgium",
       "flag":"🇧🇪",
       "code":"BE",
       "dial_code":"+32"
    },
    {
       "name":"Belize",
       "flag":"🇧🇿",
       "code":"BZ",
       "dial_code":"+501"
    },
    {
       "name":"Benin",
       "flag":"🇧🇯",
       "code":"BJ",
       "dial_code":"+229"
    },
    {
       "name":"Bermuda",
       "flag":"🇧🇲",
       "code":"BM",
       "dial_code":"+1441"
    },
    {
       "name":"Bhutan",
       "flag":"🇧🇹",
       "code":"BT",
       "dial_code":"+975"
    },
    {
       "name":"Bolivia, Plurinational State of bolivia",
       "flag":"🇧🇴",
       "code":"BO",
       "dial_code":"+591"
    },
    {
       "name":"Bosnia and Herzegovina",
       "flag":"🇧🇦",
       "code":"BA",
       "dial_code":"+387"
    },
    {
       "name":"Botswana",
       "flag":"🇧🇼",
       "code":"BW",
       "dial_code":"+267"
    },
    {
       "name":"Bouvet Island",
       "flag":"🇧🇻",
       "code":"BV",
       "dial_code":"+47"
    },
    {
       "name":"Brazil",
       "flag":"🇧🇷",
       "code":"BR",
       "dial_code":"+55"
    },
    {
       "name":"British Indian Ocean Territory",
       "flag":"🇮🇴",
       "code":"IO",
       "dial_code":"+246"
    },
    {
       "name":"Brunei Darussalam",
       "flag":"🇧🇳",
       "code":"BN",
       "dial_code":"+673"
    },
    {
       "name":"Bulgaria",
       "flag":"🇧🇬",
       "code":"BG",
       "dial_code":"+359"
    }
 ]